# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
import my_excersice

class Ui_ExerciseProgram(object):
    def setupUi(self, ExerciseProgram):
        ExerciseProgram.setObjectName("ExerciseProgram")
        ExerciseProgram.resize(600, 400)
        self.centralwidget = QtWidgets.QWidget(ExerciseProgram)
        self.centralwidget.setObjectName("centralwidget")
        self.squad = QtWidgets.QPushButton(self.centralwidget)
        self.squad.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.squad.setObjectName("squad")
        self.high_knees = QtWidgets.QPushButton(self.centralwidget)
        self.high_knees.setGeometry(QtCore.QRect(30, 90, 75, 23))
        self.high_knees.setObjectName("high_knees")
        self.leg_curls = QtWidgets.QPushButton(self.centralwidget)
        self.leg_curls.setGeometry(QtCore.QRect(30, 130, 75, 23))
        self.leg_curls.setObjectName("leg_curls")
        self.punches = QtWidgets.QPushButton(self.centralwidget)
        self.punches.setGeometry(QtCore.QRect(30, 170, 75, 23))
        self.punches.setObjectName("punches")
        self.elbow_plank = QtWidgets.QPushButton(self.centralwidget)
        self.elbow_plank.setGeometry(QtCore.QRect(30, 210, 75, 23))
        self.elbow_plank.setObjectName("elbow_plank")
        self.chest_squeeze = QtWidgets.QPushButton(self.centralwidget)
        self.chest_squeeze.setGeometry(QtCore.QRect(30, 250, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.chest_squeeze.setFont(font)
        self.chest_squeeze.setObjectName("chest_squeeze")
        self.superman = QtWidgets.QPushButton(self.centralwidget)
        self.superman.setGeometry(QtCore.QRect(30, 290, 75, 23))
        self.superman.setObjectName("superman")
        self.example = QtWidgets.QLabel(self.centralwidget)
        self.example.setGeometry(QtCore.QRect(250, 60, 240, 260))
        self.example.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.example.setText("")
        self.example.setScaledContents(False)
        self.example.setAlignment(QtCore.Qt.AlignCenter)
        self.example.setObjectName("example")
        self.stop = QtWidgets.QLabel(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(250, 360, 75, 23))
        self.stop.setObjectName("Spot")
        ExerciseProgram.setCentralWidget(self.centralwidget)

        self.retranslateUi(ExerciseProgram)
        QtCore.QMetaObject.connectSlotsByName(ExerciseProgram)

    def retranslateUi(self, ExerciseProgram):
        _translate = QtCore.QCoreApplication.translate
        ExerciseProgram.setWindowTitle(_translate("ExerciseProgram", "MainWindow"))
        self.squad.setText(_translate("ExerciseProgram", "Squad"))
        self.high_knees.setText(_translate("ExerciseProgram", "High Knees"))
        self.leg_curls.setText(_translate("ExerciseProgram", "Leg Curls"))
        self.punches.setText(_translate("ExerciseProgram", "Punches"))
        self.elbow_plank.setText(_translate("ExerciseProgram", "Elbow Plank"))
        self.chest_squeeze.setText(_translate("ExerciseProgram", "Chest Squeeze"))
        self.superman.setText(_translate("ExerciseProgram", "Superman"))
        self.stop.setText(_translate("ExerciseProgram", "Press Q to Stop"))

        self.squad.clicked.connect(self.Squat)
        self.high_knees.clicked.connect(self.HighKnees)
        self.leg_curls.clicked.connect(self.LegCurl)
        self.punches.clicked.connect(self.Punches)
        self.elbow_plank.clicked.connect(self.Plank)
        self.chest_squeeze.clicked.connect(self.ChestSqueeze)
        self.superman.clicked.connect(self.Superman)
    

    def Squat(self):
        pixmap = QPixmap('examples/squat.png')
        self.example.setPixmap(pixmap)
        my_excersice.Squat()
        
    def HighKnees(self):
        pixmap = QPixmap('examples/high_knees.png')
        self.example.setPixmap(pixmap)
        my_excersice.HighKnees()

    def LegCurl(self):
        pixmap = QPixmap('examples/leg_curls.png')
        self.example.setPixmap(pixmap)
        my_excersice.LegCurl()

    def Punches(self):
        pixmap = QPixmap('examples/punches.png')
        self.example.setPixmap(pixmap)
        my_excersice.Punches()

    def Plank(self):
        pixmap = QPixmap('examples/elbow_plank.png')
        self.example.setPixmap(pixmap)
        my_excersice.Plank()

    def ChestSqueeze(self):
        pixmap = QPixmap('examples/chest_squeeze.png')
        self.example.setPixmap(pixmap)
        my_excersice.CSqueeze()

    def Superman(self):
        pixmap = QPixmap('examples/superman.png')
        self.example.setPixmap(pixmap)
        my_excersice.Superman()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ExerciseProgram()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())